name = "elisa-realtor"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://adkisweuuhxdxocshkcc.supabase.co"
