name = "elisa-realtor"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
workers_dev = true

[assets]
directory = ".open-next/assets"

[[routes]]
pattern = "elisa.visibleseed.com/*"
zone_id = "7f46227ce3dcd75bad3f266ebdb82f32"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://adkisweuuhxdxocshkcc.supabase.co"
